micronaut:
  application:
    name: backend
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      media:
        paths:
          - file:${MEDIA_STORAGE_PATH:../../storage/media}
        mapping: /media/**
  server:
    cors:
      enabled: true
      configurations:
        default:
          paths:
            - /**
          allowed-origins:
            - http://localhost:5173
            - ${FRONTEND_URL:`http://localhost:5000`}
          allowed-methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
            - X-Requested-With
            - Accept
            - Origin
          exposed-headers:
            - Content-Type
            - Authorization
          allow-credentials: true
          max-age-seconds: 1800
        ui:
          paths:
            - /swagger-ui/**
          allowed-origins:
            - ${ FRONTEND_URL:`http://localhost:5000` }
datasources:
  default:
    url: ${ JDBC_URL:`jdbc:h2:mem:testedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE` }
    driver-class-name: ${JDBC_DRIVER:org.h2.Driver}
    dialect: ${ JDBC_DIALECT:H2 }
    db-type: ${ JDBC_DB_TYPE:h2 }
    username: ${ JDBC_USERNAME:sa }
    password: ${ JDBC_PASSWORD:"" }
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
media:
  upload:
    dir: ${MEDIA_STORAGE_PATH:../../storage/media}
  base-url: ${MEDIA_BASE_URL:`http://localhost:8080/media/`}
  storage:
    type: local
jpa:
  default:
    entity-scan:
      packages: mn_react.backend.entities
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true